add implementation
dvpnt/eslint-plugin-pathnames pull request #1
Opened 2020-08-11 14:09 UTC by qlba

2020-08-13 11:14 UTC, psixdev requested changes

2020-08-13 11:14 UTC, psixdev commented on lib/index.js
> +const pkgDir = require('pkg-dir').sync;
`const {sync: pkgDir} = ...`

2020-08-13 11:14 UTC, psixdev commented on test/lib.js
> +const {match} = require('../lib').rules;
Это желательно тоже поправить, возможно экспортнуть просто rules

2020-08-13 11:14 UTC, psixdev commented on package.json
> +    "test": "node test/*.js"
Что на счёт tap?

2020-08-13 11:14 UTC, psixdev commented on package.json
> +    "underscore": "^1.10.2"
Может быть стоит обойтись без underscore, он тут только ради одного места, получается

2020-08-13 11:14 UTC, psixdev commented on lib/index.js
> +			const relativePath = path.relative(pkgDir(absolutePath), absolutePath);
context.getCwd() (да и process.cwd) возвращает то же самое, что и pkgDir(absolutePath). Есть ли смысл тут использовать именно pkgDir?

2020-08-13 11:14 UTC, psixdev commented on lib/index.js
> +				if (folderName !== '.' && !folderRegex.test(folderName)) {
folderName же может быть '.' только в одном случае, когда relativePath === '.'? Может есть смысл проверить это вне цикла? Или есть какие-то кейсы

2020-08-13 11:14 UTC, psixdev commented on .npmrc
> +package-lock=false
Наверное это всё дело надо оформлять как либу. Добавлять package-lock, убирать nvmrc, заменять табуляции на пробелы
Возможно отдельной задачей

2020-08-13 11:14 UTC, psixdev commented on test/lib.js
> +};
Может надо рассмотреть случаи, когда эти параметры вообще не подаются?

2020-08-13 11:14 UTC, psixdev commented on package.json
> +  "version": "0.0.0",
0.0.1 или 1.0.0

2020-08-13 11:14 UTC, psixdev commented on package.json
> +    "eslint-plugin-node": "^11.1.0"
Может для dev неплохо было бы и строгие зависимости определить. Какой смысл поддерживать несколько версий

2020-08-13 11:18 UTC, qlba commented on test/lib.js
> +const {match} = require('../lib').rules;
Ну для плагинов eslint должен быть формат `{rules: {rule1: {meta, create}, ...}}`, то есть иначе для этого отдельный файл придется делать

2020-08-13 11:22 UTC, psixdev commented on test/lib.js
> +const {match} = require('../lib').rules;
импортнуть*

2020-08-13 11:25 UTC, qlba commented on package.json
> +    "test": "node test/*.js"
Ну в принципе можно, но там даже для кейсов сложно названия придумать

2020-08-13 11:27 UTC, qlba commented on package.json
> +    "underscore": "^1.10.2"
Я тоже об этом думал
Нужно комиссию собрать и решить, можно ли использовать `array.forEach`

2020-08-13 11:32 UTC, qlba commented on lib/index.js
> +			const relativePath = path.relative(pkgDir(absolutePath), absolutePath);
Ну тут решается проблема с тем, если eslint запущен извне проекта

2020-08-13 11:39 UTC, qlba commented on lib/index.js
> +				if (folderName !== '.' && !folderRegex.test(folderName)) {
Да, только relativePath не `'.'`, а любая строка, не содержащая `/`, тогда dirname возвращает `'.'`
Может смысл и есть, но тогда придется или `path.dirname(relativePath)` выносить, или `relativePath.indexOf('/') < 0`

2020-08-13 11:44 UTC, qlba commented on test/lib.js
> +};
`ignorePaths` да, можно убрать
А если не будет `fileNames`, то исключение вылетит (ошибка валидации), а исключения RuleTester не ловит

2020-08-13 11:47 UTC, psixdev commented on lib/index.js
> +			const relativePath = path.relative(pkgDir(absolutePath), absolutePath);
Так. А если пытаться линтить файл вообще не из проекта, это будет работать?
Ну и возможно это совсем не важные кейсы

2020-08-13 11:49 UTC, psixdev commented on lib/index.js
> +				if (folderName !== '.' && !folderRegex.test(folderName)) {
>  придется или path.dirname(relativePath) выносить

звучит как план

2020-09-14 14:10 UTC, fleg requested changes

2020-09-14 14:10 UTC, fleg commented on .eslintrc.json
> +  "extends": "fbjs-opensource",
использовать наш конфиг (да, с табуляциями)

2020-09-14 14:10 UTC, fleg commented on lib/__tests__/index.js
> +      // testing an individual case requires following workaround
интересно, почему бы не сделать это как предполагает RuleTester?

2020-09-14 14:10 UTC, fleg commented on package.json
> +  "license": "UNLICENSED",
mit

2020-09-14 14:10 UTC, fleg commented on package.json
> +  "license": "UNLICENSED",
и добавить саму лицензию

2020-09-14 14:25 UTC, qlba commented on .eslintrc.json
> +  "extends": "fbjs-opensource",
https://github.com/dvpnt/eslint-plugin-pathnames/pull/1#discussion_r469873656
@psixdev

2020-09-14 14:26 UTC, qlba commented on lib/__tests__/index.js
> +      // testing an individual case requires following workaround
Ну потому что тогда придется все кейсы в одном ассерте тестировать

2020-09-14 14:35 UTC, fleg commented on lib/__tests__/index.js
> +      // testing an individual case requires following workaround
если при этом он кидает осмысленные ошибки, чтобы понять какой кейс сломан, то я думаю это не проблема

2020-09-14 14:44 UTC, psixdev commented on package-lock.json
> +  "version": "0.0.1",
Тут неверная версия?

2020-09-14 14:45 UTC, psixdev commented on package-lock.json
> +  "version": "0.0.1",
У меня после `npm i` появляется diff

2020-09-14 14:47 UTC, psixdev commented on README.md
> +        "ignorePaths": "..."
Может тут реальные примеры добавить?

2020-09-14 15:13 UTC, psixdev commented on .eslintrc.json
> +  "extends": "fbjs-opensource",
Про замену табуляций пробелами я поспешил, думал, что мы начали оформлять либы пробелами. Не начали
В остальном актуально, нужен наш конфиг. Основной код не в нашем стиле написан и это проблема, независимо от того, либа это или не либа

2020-09-15 07:33 UTC, qlba commented on lib/__tests__/index.js
> +      // testing an individual case requires following workaround
Главная проблема что все кейсы в него без названия передаются

2020-09-15 07:52 UTC, fleg commented on lib/__tests__/index.js
> +      // testing an individual case requires following workaround
не выглядит как большая проблема, необязательно тестировать каждый случай отдельным ассертом со своим названием, у нас есть вполне удобный (очень хочется верить, если они его сами используют) инструмент для тестирования правил, и почему бы тут его не применить как это было задумано разработчиками eslint

2020-09-21 07:33 UTC, fleg requested changes

2020-09-21 07:33 UTC, fleg commented on lib/__tests__/index.js
> +	await t.test('configuration', async (t) => {
все тесты синхронные, нет смысла в async/await, главное не забыть про t.end()

2020-09-21 07:44 UTC, fleg approved these changes

2020-09-22 06:43 UTC, merged